### ISSUE TITLE
Colors and tab completion will improve look and fill of the resume

### ISSUE THREAD

**Issue by jcubic** [bbody/CMD-Resume#1]
to add color like white, you can put in echo: `[[;white;]text]` and to add tab completion that imrpove navigation use option: `completion` if you pass `true` it will generate commands for tab completion if you're using object or you can use array or a function that pass array to a callback.
It look like in your case you can just do:

```javascript
completion: commandFunctionMap.concat(['github', 'man', 'help', 'education', 'employment', 'volunteering', 'awards', 'memberships'])
```

**Comment by bbody** [comment]
My apologies, I didn't get notifications for this issue. I will add that feature.
