### ISSUE TITLE
Convert code into ES6

### ISSUE THREAD

**Issue by bbody** [bbody/CMD-Resume#132]

**Comment by Lockyc** [comment]
why?

**Comment by bbody** [comment]
More or less an investigation into whether it would be worth it. I think turning the build tools into it might be worth while.

**Comment by bbody** [comment]
@Lockyc at least it might be a good idea to turn my build tools into ES6, thoughts?

**Comment by Lockyc** [comment]
I suppose it would be useful as a learning exercise, but other than that it is probably unnecessary as you probably don't need any of the ES6 features and will have to compile it back to ES5 for compatibility

**Comment by bbody** [comment]
@Lockyc build tools won't need to be compiled back to ES5.

**Comment by Lockyc** [comment]
You're right

**Comment by bbody** [comment]
@Lockyc I could also use polyfill to ensure old browsers still work, given my build system is automated it might be worth it. Thoughts?

**Comment by bbody** [comment]
Blocked by testing, as it would be worthwhile to have a full suite of testing before any major code changes or refactors.

**Comment by bbody** [comment]
Given it is written with jQuery only a few of the nice parts of ES6 would be useful.
