### ISSUE TITLE
The command don't work if you type more than one space or tab

### ISSUE THREAD

**Issue by jcubic** [bbody/CMD-Resume#137]
the code use `string.split(" ");` and the commands like this `man  git` (two spaces) don't work, to fix the issue it's better to use function $.terminal.parse_command or split_command that return object:
```javascript
{
  name: 'first word',
  args: [ /* array of arguments*/],
  rest: 'command without first word',
  command: 'whole command just in case you overwrite original variable'
}
```

**Comment by bbody** [comment]
@jcubic Thanks for that, will have a look
