### ISSUE TITLE
YAML Linting for Travis config

### ISSUE THREAD

**Issue by bbody** [bbody/CMD-Resume#157]
To avoid having build issues (bad experience), lint the travis config.

**Comment by obelic2** [comment]
Using Travis' tool (https://github.com/travis-ci/travis.rb#lint), it seems to lint and validate the Travis config. I assume https://github.com/travis-ci/travis-yml is powering it

**Comment by obelic2** [comment]
https://support.travis-ci.com/hc/en-us/articles/115002904174-Validating-travis-yml-files
